apiVersion: apps/v1
kind: Deployment
metadata:
    name: calc-deployment
spec:
    selector:
       matchLabels:
          app: calc
    replicas: 2
    template:
        metadata:
           labels:
             app: calc
        spec:
         containers:
         - name: calc
           image: rajidocker2021/project:latest
           imagePullPolicy: Always
           ports:
           - containerPort: 8080
